repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
-   repo: http://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'
    hooks:
    -   id: mypy
# Security scanning hooks
-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.5'
    hooks:
    -   id: bandit
        args: ['-c', '.bandit']
        exclude: ^tests/
-   repo: https://github.com/gitguardian/ggshield
    rev: v1.25.0
    hooks:
    -   id: ggshield
        language: python
        stages: [commit]
